version: '3.4'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: circleqa
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
